name: cypress test
on: 
  push:
    branches:
      - main
  schedule:
      - cron: "10 12 * * 0-6"
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
    strategy:
      fail-fast: false
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: chrome
          start: npx cypress run 
        
