name: cypress test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.2
        with:
          start: npx cypress run --browser chrome --record --key 11233911-e9d2-4c22-b6ea-6fb6a49b5c25
          record: true
 
