name: cypress test
on: 
  push:
    branches:
      - main
  schedule:
      - cron: "10 12 * * 0-6"
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.2
        with:
          start: npx cypress run --browser chrome --record --key 3bbd09cd-3f41-4f34-8e96-2ba1c82329d0
        
