name: cypress test
on: 
  push:
    branches:
      - main
  schedule:
      - cron: "10 12 * * 0-6"
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.0
        with:
          browser: chrome
          start: npx cypress run 
        
